# Generated by Django 2.2.3 on 2019-10-05 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20190916_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='real_estate',
            old_name='like',
            new_name='likecount',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realestate_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myshop.Real_estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='real_estate',
            name='LikeUser',
            field=models.ManyToManyField(blank=True, related_name='LikeUser', through='myshop.Like', to=settings.AUTH_USER_MODEL),
        ),
    ]
