# Generated by Django 2.2.3 on 2019-12-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0005_message_send_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='recent_msg',
            field=models.BooleanField(default=False),
        ),
    ]
