# Generated by Django 2.2.3 on 2019-09-16 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='real_estate',
            name='address',
            field=models.TextField(default='Seoul, Republic of Kore', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='real_estate',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
